Traceback (most recent call last):
  File "train.py", line 150, in <module>
    check_val_every_n_epoch=5)
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/pytorch_lightning/utilities/argparse.py", line 340, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 431, in __init__
    plugins=plugins,
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 208, in __init__
    self._set_parallel_devices_and_init_accelerator()
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 542, in _set_parallel_devices_and_init_accelerator
    self._devices_flag = accelerator_cls.parse_devices(self._devices_flag)
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/pytorch_lightning/accelerators/cpu.py", line 47, in parse_devices
    devices = _parse_cpu_cores(devices)
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/lightning_lite/accelerators/cpu.py", line 85, in _parse_cpu_cores
    raise TypeError("`devices` selected with `CPUAccelerator` should be an int > 0.")
TypeError: `devices` selected with `CPUAccelerator` should be an int > 0.