GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
  | Name            | Type              | Params
------------------------------------------------------
0 | encoder_cnn     | Encoder           | 312 K
1 | decoder_cnn     | Decoder           | 514 K
2 | encoder_pos     | SoftPositionEmbed | 65.9 K
3 | decoder_pos     | SoftPositionEmbed | 576
4 | layer_norm      | LayerNorm         | 128
5 | mlp             | Sequential        | 8.3 K
6 | slots_lin       | Linear            | 12.4 K
7 | coord_quantizer | CoordQuantizer    | 5.7 K
8 | slot_attention  | SlotAttention     | 46.1 K
------------------------------------------------------
897 K     Trainable params
68.8 K    Non-trainable params
965 K     Total params
3.863     Total estimated model params size (MB)
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    trainer.fit(autoencoder, train_dataloaders=train_loader, val_dataloaders=val_loader) #, ckpt_path=dict_args['ckpt_path'])
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 604, in fit
    self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 645, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1098, in _run
    results = self._run_stage()
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1177, in _run_stage
    self._run_train()
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1190, in _run_train
    self._run_sanity_check()
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1262, in _run_sanity_check
    val_loop.run()
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 121, in advance
    batch = next(data_fetcher)
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/pytorch_lightning/utilities/fetching.py", line 184, in __next__
    return self.fetching_function()
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/pytorch_lightning/utilities/fetching.py", line 265, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/pytorch_lightning/utilities/fetching.py", line 280, in _fetch_next_batch
    batch = next(iterator)
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/slot_attention_pytorch/src/sa_autoencoder/datasets/clevr.py", line 48, in __getitem__
    img = Image.open(os.path.join(self.images_path, scene['image_filename'])).convert('RGB')
  File "/home/cosmos/PycharmProjects/CogMod-Slot-Attention/venv/lib/python3.7/site-packages/PIL/Image.py", line 3131, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/cosmos/PycharmProjects/CogMod-Slot-Attention/datasets/CLEVR_v.1.0/images/val/CLEVR_val_000004.png'
Sanity Checking: 0it [00:00, ?it/s]